theme: jekyll-theme-architect
#site:
title:呆呆和晓晓的小屋
description:用来记录我和晓晓生活中的点点滴滴
author: 浩哥
language: zh-CN

menu:  #导航栏
  主页: /
  归档: /archives
  关于: /about  #介绍一下你自己
  网络工具: /tools  #自己添加
  资源共享: /share  #自己添加

widgets:  ## 右边的零部件，jacman主题提供了7个：category、tag、rss、archive、tagcloud、links、weibo、douban，可以根据自己喜好增减
- category  #目录
- tagcloud  #标签云（也可以选用标签，上面显示数值）
- links  #友情链接，需要自己添加，下一篇再说
- rss  #RSS你们都知道的
- weibo  #微博秀，需要在微博上开通，下一篇再说

作者：起今知行
链接：http://www.jianshu.com/p/db7e64d86067
來源：简书
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
